# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWBtoeBF0K0vJ8QVhKqaNX0c_BkXlLYz
"""

!pip install -q \
pinecone \
langchain \
langchain-community \
langchain-huggingface \
sentence-transformers \
pypdf



!pip install -U langchain langchain-core langchain-text-splitters langchain-huggingface langchain-pinecone pypdf sentence-transformers pinecone

from langchain_community.document_loaders import PyPDFLoader

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_huggingface import HuggingFaceEmbeddings

from pinecone import Pinecone, ServerlessSpec

from langchain_pinecone import PineconeVectorStore

import os

loader = PyPDFLoader("RAGPaper.pdf")

documents = loader.load()

print(len(documents))

print(documents[0].page_content)

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

docs = splitter.split_documents(documents)

len(docs)

print(docs[0].page_content)

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vector = embedding_model.embed_query("What is RAG?")

print(len(vector))

PINECONE_API_KEY = "pcsk_6cBKqx_JcZxd8EGXrGaAgUJEPQCu9VWzZ1iznSGBWZrpZb7TjZS6oWPV3XT5vQpowAKNF1"

pc = Pinecone(api_key=PINECONE_API_KEY)

index_name = "rag-paper"

if index_name not in pc.list_indexes().names():

    pc.create_index(
        name=index_name,
        dimension=384,
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )

vectorstore = PineconeVectorStore(
    index_name=index_name,
    embedding=embedding_model,
    pinecone_api_key=PINECONE_API_KEY
)

vectorstore.add_documents(docs)

query = "What is Retrieval Augmented Generation?"

results = vectorstore.similarity_search(query, k=3)

for i, doc in enumerate(results):
    print("="*60)
    print(i+1)
    print(doc.page_content)

results = vectorstore.similarity_search_with_score(
    query,
    k=5
)

for doc, score in results:

    print(score)
    print(doc.page_content[:300])

while True:

    question = input("Ask : ")

    if question.lower() == "exit":
        break

    docs = vectorstore.similarity_search(question, k=3)

    print()

    for doc in docs:
        print(doc.page_content)
        print("-"*50)

!pip install -q -U langchain-google-genai google-generativeai

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key="AQ.Ab8RN6Ir7QE6EnCQK4Gy-6PnN3HBjp8ezmjONewycKRq4bhusg"
)

question = "Explain RAG."

docs = vectorstore.similarity_search(question, k=3)

context = "\n\n".join([d.page_content for d in docs])

prompt = f"""
Answer only using the context.

Context:

{context}

Question:

{question}
"""

response = llm.invoke(prompt)

print(response.content)

